//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDS207_Project.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MIDS207_Project.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio César Guzmán Cortés.
        /// </summary>
        public static string Footer_Title1 {
            get {
                return ResourceManager.GetString("Footer-Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea que el alumno este activo?.
        /// </summary>
        public static string Student_Active_Label {
            get {
                return ResourceManager.GetString("Student_Active_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agregar alumno.
        /// </summary>
        public static string Student_Add {
            get {
                return ResourceManager.GetString("Student_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento *.
        /// </summary>
        public static string Student_BirthDate_Label {
            get {
                return ResourceManager.GetString("Student_BirthDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Student_Close {
            get {
                return ResourceManager.GetString("Student_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal.
        /// </summary>
        public static string Student_CP_Label {
            get {
                return ResourceManager.GetString("Student_CP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código postal consta de 5 dígitos.
        /// </summary>
        public static string Student_CP_Placeholder {
            get {
                return ResourceManager.GetString("Student_CP_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURP.
        /// </summary>
        public static string Student_CURP_Label {
            get {
                return ResourceManager.GetString("Student_CURP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El CURP no es válido, verifique.
        /// </summary>
        public static string Student_CURP_Title {
            get {
                return ResourceManager.GetString("Student_CURP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico *.
        /// </summary>
        public static string Student_Email_Label {
            get {
                return ResourceManager.GetString("Student_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del alumno.
        /// </summary>
        public static string Student_Fieldset {
            get {
                return ResourceManager.GetString("Student_Fieldset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer archivo *.
        /// </summary>
        public static string Student_File1_Label {
            get {
                return ResourceManager.GetString("Student_File1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo archivo *.
        /// </summary>
        public static string Student_File2_Label {
            get {
                return ResourceManager.GetString("Student_File2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercer archivo *.
        /// </summary>
        public static string Student_File3_Label {
            get {
                return ResourceManager.GetString("Student_File3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer nombre *.
        /// </summary>
        public static string Student_FirstName_Label {
            get {
                return ResourceManager.GetString("Student_FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género *.
        /// </summary>
        public static string Student_Gender_Label {
            get {
                return ResourceManager.GetString("Student_Gender_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione uno....
        /// </summary>
        public static string Student_Gender_Placeholder {
            get {
                return ResourceManager.GetString("Student_Gender_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Student_LastName_Label {
            get {
                return ResourceManager.GetString("Student_LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo nombre.
        /// </summary>
        public static string Student_MiddleName_Label {
            get {
                return ResourceManager.GetString("Student_MiddleName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Student_Ok {
            get {
                return ResourceManager.GetString("Student_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña *.
        /// </summary>
        public static string Student_Password_Label {
            get {
                return ResourceManager.GetString("Student_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número teléfonico.
        /// </summary>
        public static string Student_PhoneNumber_Label {
            get {
                return ResourceManager.GetString("Student_PhoneNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir contraseña *.
        /// </summary>
        public static string Student_RepeatPassword_Label {
            get {
                return ResourceManager.GetString("Student_RepeatPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC.
        /// </summary>
        public static string Student_RFC_Label {
            get {
                return ResourceManager.GetString("Student_RFC_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El RFC no es válido, verifique.
        /// </summary>
        public static string Student_RFC_Title {
            get {
                return ResourceManager.GetString("Student_RFC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Student_Save {
            get {
                return ResourceManager.GetString("Student_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por nombre....
        /// </summary>
        public static string Student_Search_Placeholder {
            get {
                return ResourceManager.GetString("Student_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento.
        /// </summary>
        public static string Student_Search_ThBirthDate {
            get {
                return ResourceManager.GetString("Student_Search_ThBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        public static string Student_Search_ThCP {
            get {
                return ResourceManager.GetString("Student_Search_ThCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURP.
        /// </summary>
        public static string Student_Search_ThCURP {
            get {
                return ResourceManager.GetString("Student_Search_ThCURP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Student_Search_ThEmail {
            get {
                return ResourceManager.GetString("Student_Search_ThEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos.
        /// </summary>
        public static string Student_Search_ThFiles {
            get {
                return ResourceManager.GetString("Student_Search_ThFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string Student_Search_ThGender {
            get {
                return ResourceManager.GetString("Student_Search_ThGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Student_Search_ThLastName {
            get {
                return ResourceManager.GetString("Student_Search_ThLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Student_Search_ThName {
            get {
                return ResourceManager.GetString("Student_Search_ThName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Student_Search_ThPhoneNumber {
            get {
                return ResourceManager.GetString("Student_Search_ThPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC.
        /// </summary>
        public static string Student_Search_ThRFC {
            get {
                return ResourceManager.GetString("Student_Search_ThRFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Student_Search_ThState {
            get {
                return ResourceManager.GetString("Student_Search_ThState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string Student_Search_ThStatus {
            get {
                return ResourceManager.GetString("Student_Search_ThStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Student_State_Label {
            get {
                return ResourceManager.GetString("Student_State_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione uno....
        /// </summary>
        public static string Student_State_Placeholder {
            get {
                return ResourceManager.GetString("Student_State_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Student_Tab_Search {
            get {
                return ResourceManager.GetString("Student_Tab_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Buscar!.
        /// </summary>
        public static string Student_Tab_Search2 {
            get {
                return ResourceManager.GetString("Student_Tab_Search2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumno.
        /// </summary>
        public static string Student_Tab_Student {
            get {
                return ResourceManager.GetString("Student_Tab_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver archivo.
        /// </summary>
        public static string Student_ViewFile_Label {
            get {
                return ResourceManager.GetString("Student_ViewFile_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colegio de Postgrado en desarrollo de Software.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDS 207 - Programación y Desarrollo Web.
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
    }
}
